In [16]:
import pandas as pd
import numpy as np
import re 
import nltk
import gensim
from gensim.models import Word2Vec,keyedvectors
from gensim.utils import simple_preprocess

In [2]:
model_path=r"C:\Users\aksha\Downloads\GoogleNews-vectors-negative300.bin.gz"
model=keyedvectors.load_word2vec_format(model_path,binary=True)

In [3]:
model.most_similar('king')

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422105193138123)]

In [9]:
model.most_similar('draft')

[('Draft', 0.7898759841918945),
 ('drafted', 0.7554892897605896),
 ('drafts', 0.7104418277740479),
 ('drafting', 0.7026752233505249),
 ('NFL_Draft', 0.6088486313819885),
 ('draft_pick', 0.6017876863479614),
 ('*_Withdrew', 0.5991345047950745),
 ('firstround_draft', 0.5819916725158691),
 ('NBA_Draft', 0.5809031128883362),
 ('Drafted', 0.5793238878250122)]

In [10]:
model['king']

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [60]:
df=pd.read_csv(r"D:\CognoRise\spam\spam.csv")
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [15]:
from nltk.stem import WordNetLemmatizer
lema=WordNetLemmatizer()
from nltk import sent_tokenize

In [13]:
corpus=[]
for i in range(0,len(df)):
    review=re.sub('[^a-zA-Z]',' ',df['Message'][i])
    review=review.lower()
    review=review.split()
    review=[lema.lemmatize(word) for word in review ]
    review=' '.join(review)
    corpus.append(review)

In [14]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [17]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [18]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [20]:
# train word2vec from scratch
model=gensim.models.Word2Vec(words,vector_size=100)

In [21]:
# to get al the vocabulary
model.wv.index_to_key

['to',
 'you',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'if',
 'will',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'go',
 'lt',
 'how',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'time',
 'good',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'she',
 'home',
 'stop',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'our',
 'dont',
 'think',
 'tell',
 'phone',
 'hi',
 'week',
 'new',
 'they',
 'later',
 'please',
 'pls',
 'ha',
 'her',
 'any',
 'did',
 'co',
 'been',
 'msg',
 'min',
 'an',
 'some',
 'dear',
 'make',
 'night',
 'who',
 'here',
 'message',
 'well',
 'say',
 'where',
 're',
 'thing',
 'much',
 'oh',

In [22]:
model.corpus_count

5569

In [23]:
model.epochs

5

In [24]:
model.wv.similar_by_word('kid')

[('wish', 0.9959479570388794),
 ('my', 0.9958311915397644),
 ('would', 0.9958240985870361),
 ('miss', 0.9957749247550964),
 ('too', 0.9957377910614014),
 ('well', 0.9957332611083984),
 ('and', 0.9957155585289001),
 ('feel', 0.9956822395324707),
 ('better', 0.9956412315368652),
 ('tell', 0.9956366419792175)]

In [25]:
model.wv.most_similar('hi')

[('hello', 0.997855544090271),
 ('say', 0.9978291988372803),
 ('mean', 0.9977738261222839),
 ('ve', 0.9977226257324219),
 ('money', 0.9976592063903809),
 ('wa', 0.9976389408111572),
 ('im', 0.9976136088371277),
 ('here', 0.9976032376289368),
 ('hey', 0.997590184211731),
 ('some', 0.9975847005844116)]

In [26]:
model.wv['good']

array([-0.20632847,  0.24624588,  0.10704289,  0.17290051,  0.11338539,
       -0.72074485,  0.2948973 ,  0.7637385 , -0.38330498, -0.19014354,
       -0.18768293, -0.5217237 , -0.07110754,  0.22495678,  0.3723294 ,
       -0.30238083,  0.08671474, -0.45428678, -0.13899708, -0.7503433 ,
        0.27192512,  0.2076582 ,  0.19981144, -0.33852923, -0.09760682,
        0.03370317, -0.37750813, -0.36077112, -0.3540731 ,  0.03437773,
        0.56269056,  0.00838225,  0.09709937, -0.15696903, -0.20617801,
        0.5597441 , -0.09069857, -0.37403843, -0.3095758 , -0.55733865,
        0.14371355, -0.22985339, -0.20759782, -0.11606119,  0.3627172 ,
       -0.05862381, -0.22463743, -0.2834415 ,  0.20069045,  0.2109233 ,
        0.25223982, -0.28272432, -0.06732941,  0.17914177, -0.22858687,
        0.2899287 ,  0.27511868,  0.17211041, -0.3348985 ,  0.26965585,
        0.05889354,  0.09894682,  0.03921206, -0.16388762, -0.43504354,
        0.34073403,  0.11476404,  0.4072591 , -0.5557161 ,  0.42

In [27]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [33]:
avg_word2vec(words[1])

0.0046640933

In [30]:
from tqdm import tqdm

In [48]:
def avg_word2vec(doc):
    # Filter words to only those in the model's vocabulary
    valid_words = [model.wv[word] for word in doc if word in model.wv.index_to_key]
    
    if valid_words:
        return np.mean(valid_words, axis=0)
    else:
        # Return a zero vector if no valid words are found
        return np.zeros(model.wv.vector_size)
x = []
for i in tqdm(range(len(words))):
    x.append(avg_word2vec(words[i]))

100%|██████████| 5569/5569 [00:00<00:00, 5964.20it/s]


In [49]:
x

[array([-0.12487822,  0.19367293,  0.05780794,  0.10799602,  0.05478113,
        -0.51882225,  0.20300193,  0.5342283 , -0.28174943, -0.11537202,
        -0.1472571 , -0.3627725 , -0.04557403,  0.14950323,  0.25074437,
        -0.2056776 ,  0.05285901, -0.3446514 , -0.09248015, -0.54171413,
         0.18559971,  0.14889193,  0.14629023, -0.22222027, -0.07530626,
         0.02273705, -0.27212575, -0.24525394, -0.24317412,  0.02424286,
         0.3679152 , -0.0048385 ,  0.05291264, -0.125983  , -0.13276428,
         0.38439402, -0.05936259, -0.26813096, -0.24357957, -0.40275005,
         0.08450571, -0.15639922, -0.15024523, -0.08263072,  0.2541381 ,
        -0.04202714, -0.15944585, -0.20403409,  0.14906476,  0.15242647,
         0.16431735, -0.19370382, -0.04500218,  0.12574229, -0.16314642,
         0.18750222,  0.1901612 ,  0.11597317, -0.24844275,  0.17951114,
         0.0395737 ,  0.05176216,  0.03482059, -0.10684201, -0.30519983,
         0.25200564,  0.08371387,  0.29247576, -0.3

In [50]:
avg_word2vec(words[1])

array([-0.11052369,  0.1747657 ,  0.03930065,  0.09512806,  0.04951502,
       -0.44634447,  0.17175846,  0.44822115, -0.23521048, -0.09157961,
       -0.12437904, -0.3078753 , -0.03582274,  0.13419154,  0.21353388,
       -0.178797  ,  0.04727994, -0.2928403 , -0.07936131, -0.46684623,
        0.16295484,  0.12326907,  0.11365914, -0.19087204, -0.06128851,
        0.01484472, -0.22752175, -0.21339723, -0.20410281,  0.01730738,
        0.31353885, -0.00158876,  0.0395416 , -0.10956334, -0.11238897,
        0.32179222, -0.05063391, -0.22198635, -0.20809296, -0.3518698 ,
        0.07954716, -0.12452847, -0.12510207, -0.07672146,  0.2090956 ,
       -0.03260805, -0.136524  , -0.17019977,  0.13182172,  0.13000911,
        0.13562942, -0.1645681 , -0.03953505,  0.10727376, -0.13684103,
        0.15848035,  0.16615847,  0.10348368, -0.2139546 ,  0.15867445,
        0.03551418,  0.04792373,  0.02837803, -0.09156164, -0.26127458,
        0.20920323,  0.0756836 ,  0.24691467, -0.3311572 ,  0.25

In [51]:
len(x)

5569

In [52]:
np.array(x)

array([[-0.12487822,  0.19367293,  0.05780794, ..., -0.20272678,
         0.17727727, -0.01907138],
       [-0.11052369,  0.17476571,  0.03930065, ..., -0.18429498,
         0.15920329, -0.0119838 ],
       [-0.10785358,  0.21873929,  0.06215955, ..., -0.21236056,
         0.18276057, -0.01373587],
       ...,
       [-0.17358072,  0.25233501,  0.08480059, ..., -0.26890969,
         0.23248316, -0.02893412],
       [-0.1529146 ,  0.23457873,  0.07219332, ..., -0.24678567,
         0.21169138, -0.02841154],
       [-0.17499322,  0.24355118,  0.0704243 , ..., -0.27220935,
         0.23086531, -0.02441438]])

In [53]:
x_new=np.array(x)

In [83]:
newdf=pd.DataFrame(x_new)

In [84]:
newdf

0         1         2         3         4         5         6   \
0    -0.124878  0.193673  0.057808  0.107996  0.054781 -0.518822  0.203002   
1    -0.110524  0.174766  0.039301  0.095128  0.049515 -0.446344  0.171758   
2    -0.107854  0.218739  0.062160  0.131571  0.062333 -0.581119  0.191862   
3    -0.179517  0.265987  0.069338  0.148554  0.069151 -0.685233  0.280230   
4    -0.158954  0.221548  0.064192  0.129864  0.068479 -0.584921  0.232937   
...        ...       ...       ...       ...       ...       ...       ...   
5564 -0.119951  0.247481  0.083973  0.135737  0.079735 -0.659082  0.229045   
5565 -0.158596  0.235384  0.062972  0.144705  0.074767 -0.629206  0.236542   
5566 -0.173581  0.252335  0.084801  0.144028  0.070311 -0.687971  0.271358   
5567 -0.152915  0.234579  0.072193  0.137932  0.067947 -0.629438  0.240140   
5568 -0.174993  0.243551  0.070424  0.150575  0.074806 -0.661181  0.249000   

            7         8         9   ...        90        91        92  \
0     0.534228 -0.281749 -0.115372  ...  0.342083  0.131848  0.056050   
1     0.448221 -0.235210 -0.091580  ...  0.289295  0.108454  0.044170   
2     0.547458 -0.287739 -0.097348  ...  0.347046  0.128532  0.044257   
3     0.715388 -0.379241 -0.152541  ...  0.456687  0.170241  0.068816   
4     0.613745 -0.323174 -0.129765  ...  0.394334  0.145307  0.066221   
...        ...       ...       ...  ...       ...       ...       ...   
5564  0.640161 -0.333864 -0.127358  ...  0.409766  0.150089  0.066252   
5565  0.637572 -0.343777 -0.124796  ...  0.413803  0.157145  0.056299   
5566  0.716073 -0.380578 -0.165588  ...  0.463298  0.179983  0.080625   
5567  0.644346 -0.342182 -0.139393  ...  0.411621  0.158641  0.073204   
5568  0.687586 -0.364629 -0.144298  ...  0.439719  0.161860  0.076954   

            93        94        95        96        97        98        99  
0     0.044971  0.454179  0.259940  0.076355 -0.202727  0.177277 -0.019071  
1     0.034643  0.378491  0.224097  0.063566 -0.184295  0.159203 -0.011984  
2     0.044627  0.462236  0.246906  0.041225 -0.212361  0.182761 -0.013736  
3     0.059549  0.599677  0.357380  0.111312 -0.283800  0.240103 -0.013899  
4     0.055893  0.519926  0.311157  0.088556 -0.246575  0.211202 -0.021048  
...        ...       ...       ...       ...       ...       ...       ...  
5564  0.061620  0.541692  0.296618  0.074395 -0.238601  0.204378 -0.014789  
5565  0.050661  0.551570  0.312703  0.082913 -0.258531  0.217838 -0.021571  
5566  0.061767  0.609687  0.356663  0.115532 -0.268910  0.232483 -0.028934  
5567  0.054985  0.549567  0.316236  0.088299 -0.246786  0.211691 -0.028412  
5568  0.053595  0.578116  0.341850  0.098175 -0.272209  0.230865 -0.024414  

[5569 rows x 100 columns]

In [85]:
newdf.shape

(5569, 100)

In [77]:
corpus[1]

'ok lar joking wif u oni'

In [70]:
y=df[list(map(lambda x: len(x)>0,corpus))]
y=pd.get_dummies(y['Category'])

In [71]:
y

ham  spam
0       1     0
1       1     0
2       0     1
3       1     0
4       1     0
...   ...   ...
5567    0     1
5568    1     0
5569    1     0
5570    1     0
5571    1     0

[5569 rows x 2 columns]

In [99]:
target=y[['ham']]

In [100]:
target

ham
0       1
1       1
2       0
3       1
4       1
...   ...
5567    0
5568    1
5569    1
5570    1
5571    1

[5569 rows x 1 columns]

In [101]:
from sklearn.model_selection import train_test_split

In [102]:
x_train,x_test,y_train,y_test=train_test_split(newdf,target,train_size=0.8)

In [103]:
x_train.shape

(4455, 100)

In [104]:
y_train.shape

(4455, 1)

In [105]:
x_test.shape

(1114, 100)

In [106]:
y_test.shape

(1114, 1)

In [111]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,accuracy_score

In [110]:
randomfor=RandomForestClassifier().fit(x_train,y_train)

C:\Users\aksha\anaconda3\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


In [113]:
train_predt=randomfor.predict(x_train)
print(accuracy_score(y_train,train_predt))
print(classification_report(y_train,train_predt))

0.9997755331088665
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       599
           1       1.00      1.00      1.00      3856

    accuracy                           1.00      4455
   macro avg       1.00      1.00      1.00      4455
weighted avg       1.00      1.00      1.00      4455



In [114]:
test_predt=randomfor.predict(x_test)
print(accuracy_score(y_test,test_predt))
print(classification_report(y_test,test_predt))

0.9631956912028725
              precision    recall  f1-score   support

           0       0.86      0.86      0.86       148
           1       0.98      0.98      0.98       966

    accuracy                           0.96      1114
   macro avg       0.92      0.92      0.92      1114
weighted avg       0.96      0.96      0.96      1114

